### ISSUE TITLE
Missing Lectorial Slides

### ISSUE THREAD

**Issue by HenryLyu** [rvss-australia/RVSS#2]
Dear Organizers, 

Thank you very much for hosting this wonderful event! The lecturial and deep dive contents are very comprehensive and helpful.

I noticed that some lecturial slides haven't been uploaded (B2, B3, D3). Would you please kindly upload these slides? This would be very helpful for revision and further exploration.

Thanks!

**Comment by doda42** [comment]
Thanks for your patience, all slides should be up now. If you notice any issues don't hesitate to reach out.
